apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-scaled
  namespace: d365-scaled-selenium-testing
  labels:
    app: selenium-hub-scaled
spec:
  type: NodePort
  selector:
    app: selenium-hub-scaled
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 32000
      name: selenium-hub-port
  sessionAffinity: None
