apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: d365-scaled-selenium-testing
  labels:
    app: selenium-node-chrome
spec:
  replicas: 5
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:3.141
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: HUB_HOST
              value: "selenium-hub-scaled"
            - name: HUB_PORT
              value: "4444"
